### ISSUE TITLE
Posar un comptador al principi

### ISSUE THREAD

**Issue by and4po** [JoanRiosiPla/BENEIT#10]
Estaria molt bé posar un comptador dels insults a la part superior del lloc web amb un missatge com: «tenim _**72**_ insults a la nostra base de dades, vols ajudar a afegir-ne…»

PS: Puc provar de fer-lo jo mateix si trobo una mica de temps un d'aquests dies, però ho deixo per aquí com a suggeriment.

**Comment by JoanRiosiPla** [comment]
Em sembla bona idea. El mateix dic, si tinc temps ho implementaré i avisaré per ací.

**Comment by and4po** [comment]
Fet amb un PR fa una estoneta!

**Comment by JoanRiosiPla** [comment]
Genial! Marque l'issue com a completat.
